# yazi.toml

[manager]
ratio = [2, 2, 4]

[opener]
edit = [
  { run = 'nu ~/.config/yazelix/nushell/open_file.nu "$1"', desc = "Open File in a new pane" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
