# Elixir
[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "elixir"
file-types = ["ex", "exs", "heex"]
shebangs = ["elixir"]
roots = ["mix.exs"]
comment-token = "#"
language-servers = ["elixir-ls"]
auto-format = true

# Erlang
[[language]]
name = "erlang"
scope = "source.erlang"
file-types = ["erl", "hrl"]
roots = ["rebar.config", "erlang.mk"]
language-servers = ["erlang_ls"]
auto-format = true

# Bash
[[language]]
name = "bash"
auto-format = true
language-servers = ["bash-language-server"]

# YAML
[[language]]
name = "yaml"
auto-format = true
language-servers = ["yaml-language-server"]

# Rust
[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer"]

# Ruby
[[language]]
name = "ruby"
auto-format = true
language-servers = ["solargraph"]

# Go
[[language]]
name = "go"
auto-format = true
language-servers = ["gopls"]
formatter = { command = "gofmt" }

# C/C++
[[language]]
name = "c"
auto-format = true
language-servers = ["clangd"]

[[language]]
name = "cpp"
auto-format = true
language-servers = ["clangd"]

# JavaScript/TypeScript
[[language]]
name = "javascript"
auto-format = true
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
